---
- name: check if MATLAB is installed (1)
  stat:
    path: "/usr/local/MATLAB/{{ matlab_version }}"
  register: matlab_installed

- name: check if MATLAB is installed (2)
  set_fact:
    matlab_installed: "{{ matlab_installed.stat.isdir is defined and matlab_installed.stat.isdir | bool }}"

- name: set list of license / crack files to copy for R2012b.
  set_fact:
    matlab_filelist_src: [ "activate_{{ matlab_version }}.ini", "installer_input_{{ matlab_version }}.txt", "license_standalone_{{ matlab_version }}.dat" ]
    matlab_filelist_dest: [ "activate.ini", "installer_input.txt", "license_standalone.dat" ]
    matlab_hacking_command_list: [] # no hacking
    matlab_activation_command: "/usr/local/MATLAB/R2012b/bin/activate_matlab.sh -propertiesFile /tmp/activate.ini"
  when: matlab_version == "R2012b"

- name: set list of license / crack files to copy for R2014a.
  set_fact:
    matlab_filelist_src: [ "activate_{{ matlab_version }}.ini", "installer_input_{{ matlab_version }}.txt", "license_standalone_{{ matlab_version }}.lic", "libmwservices_{{ matlab_version }}.so", "install_{{ matlab_version }}.jar" ]
    matlab_filelist_dest: [ "activate.ini", "installer_input.txt", "license_standalone.lic", "libmwservices.so", "install.jar" ]
    matlab_hacking_command_list: [ "cp /tmp/install.jar /tmp/matlab_iso/java/jar/install.jar" ] # copy install.jar
    matlab_activation_command: "cp /tmp/libmwservices.so /usr/local/MATLAB/R2014a/bin/glnxa64"
  when: matlab_version == "R2014a"

- block:  # these must finish all together in one shot.
  - name: copy all related files.
    copy:
      src: "{{ item.0 }}"
      dest: /tmp/{{ item.1 }}
      force: yes
    with_together:
      - "{{ matlab_filelist_src }}"
      - "{{ matlab_filelist_dest }}"

  - name: modify installed products
    lineinfile:
      dest: /tmp/installer_input.txt
      regexp: "#product\\.{{ item }}"
      line: "product.{{ item }}"
      backup: no
      state: present
    with_items: "{{matlab_product_list}}"

  - name: remove the folder for extraction.
    file:
      path: /tmp/matlab_iso
      state: absent
    become: True

  - name: create the folder for extraction.
    file:
      path: /tmp/matlab_iso
      state: directory
      mode: 0755

  - name: extract installer
    command: "tar xvpf {{ matlab_installer_dir }}/R2012b_UNIX.tar.gz -C /tmp/matlab_iso"
    become: True

  - name: pre install hacking
    command: "{{ item }}"
    with_items: "{{matlab_hacking_command_list}}"
    become: True

  - name: run installer
    command: "/tmp/matlab_iso/install -inputFile /tmp/installer_input.txt"
    become: True

  - name: remove the folder for extraction.
    file:
      path: /tmp/matlab_iso
      state: absent
    become: True

  - name: activate matlab
    command: "{{ matlab_activation_command }}"
    become: True

  - name: remove all related files.
    file:
      path: "/tmp/{{ item }}"
      state: absent
    with_items: "{{ matlab_filelist_dest }}"
    become: True
- rescue:  # remove installed things if something bad happens.
  - name: remove partially installed dir
    file:
      path: "/usr/local/MATLAB/{{ matlab_version }}"
      state: absent
    become: True
