os:
  - linux

# command to run tests
# first three lines are for Xserver. <https://docs.travis-ci.com/user/gui-and-headless-browsers/>
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - shell_scripts/conda/install_miniconda.sh  # install miniconda.
  - export PATH=${HOME}/miniconda2/bin:$PATH   # add path for miniconda
  - cd tests
script:
  - ./test-conda-env-common-wrapper.sh default   # for default conda env
  - ./test-conda-env-common-wrapper.sh default-3 # for python 3 default conda env
