---
- name: check it's 14.04
  assert:
    that: "{{ ansible_distribution_release == 'trusty'}}"
- name: check whether image-extra is installed.
  command: "dpkg -s linux-image-extra-{{ ansible_kernel }}"
  register: docker_kernel_result
  ignore_errors: yes
- name: make sure image-extra is installed
  assert:
    that: "{{ 'Status: install ok installed' in docker_kernel_result.stdout_lines }}"
    msg: "please install linux-image-extra-{{ ansible_kernel }} manually"
- name: apt-transport-https and ca-certificates
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present # as long as they are there, it's fine.
  with_items:
    - apt-transport-https
    - ca-certificates
- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
  register: add_repository_key
- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    update_cache: yes
    state: present
- name: install docker
  apt:
    name: docker-engine
    state: present
    update_cache: yes
- name: start docker service
  service:
    name: docker
    state: started
