---
- name: set up GPU server (yimengzh.cnbc.cmu.edu)
  hosts: all
  vars:
    # you must chanage these according to `sudo blkid`, see <https://help.ubuntu.com/community/UsingUUID>
    mount_hard_drive_mpoints: [ '/mnt/temp_drive_1', '/mnt/temp_drive_2', '/mnt/temp_drive_3' ]
    mount_hard_drive_ids: [ 'UUID=3a1e0b73-1352-42e2-a570-4e6a145283c3',  'UUID=52a6b405-4c8a-4142-bfec-e845e6060e36', 'UUID=37777524-85d8-49b0-9035-00297d59fa57']
  remote_user: yimengzh
  become: true
  # passno and dump, and options are copied from <https://help.ubuntu.com/community/InstallingANewHardDrive>
  tasks:
  - name: mount all drives
    mount:
      name: "{{ item.0 }}"
      src: "{{ item.1 }}"
      fstype: ext4
      state: mounted
      passno: 2
      dump: 0
      opts: defaults
    with_together:
      - "{{ mount_hard_drive_mpoints }}"
      - "{{ mount_hard_drive_ids }}"
  # according to <https://help.ubuntu.com/community/InstallingANewHardDrive>
  - name: make drives with correct permissions
    file:
      path: "{{ item }}"
      group: plugdev
      mode: "g+w,a+t"
    with_items: "{{ mount_hard_drive_mpoints }}"



